### ISSUE TITLE
Link caeroc.formulae.shock to caeroc.gui.runtime

### ISSUE THREAD

**Issue by ashwinvis** [ashwinvis/caeroc#1]
Allow user to use `Normal Shock` and `Oblique Shock` modes.

**Comment by ashwinvis** [comment]
Bug: cannot use `p2_p1` with normal shock mode.

```python
ERROR:caeroc-app:Insufficient data to calculate Mach number
Traceback (most recent call last):
  File "/home/avmo/src/caeroc/caeroc/gui/runtime.py", line 218, in on_qpb_calculate_released
    self.mode.calculate(**kwargs)
  File "/home/avmo/src/caeroc/caeroc/formulae/shock.py", line 81, in calculate
    self.M_1 = self.get_M_1(p2_p1, rho2_rho1, T2_T1)
  File "/home/avmo/src/caeroc/caeroc/formulae/shock.py", line 59, in get_M_1
    return M_1
UnboundLocalError: local variable 'M_1' referenced before assignment
```
